# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91cf6e1d0d32dd749e1dc7510c3961f9ec218a424c40345becb6bbffd5d853d3c8a998ef5c47cee4fdfdbd4ca4b657964a9347d8cf4808e2519daafd1860e69f

test:
  secret_key_base: 0acaf46202479ea0ae76837c7f4f7f2b08e1035eafbfe597cb895c8e255c536d65582aa626217c2de0ea5644ca447f0974631f60bdf808291951c718a01cc84c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
